"""Add CustomPlanRequest

Revision ID: 594d9547c1d5
Revises: 289a35928cb4
Create Date: 2026-05-17 21:48:58.007133
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '594d9547c1d5'
down_revision: Union[str, None] = '289a35928cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_plan_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('base_tier_id', sa.UUID(), nullable=True),
    sa.Column('diet_type', sa.Text(), nullable=False),
    sa.Column('slot_combo', sa.Text(), nullable=False),
    sa.Column('duration', sa.Text(), nullable=False),
    sa.Column('custom_requirements', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('quoted_price_per_meal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('quoted_delivery_charge', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("diet_type IN ('veg', 'nonveg', 'both')", name='ck_custom_requests_diet_type'),
    sa.CheckConstraint("duration IN ('weekly', 'monthly')", name='ck_custom_requests_duration'),
    sa.CheckConstraint("slot_combo IN ('breakfast_only', 'dinner_only', 'both')", name='ck_custom_requests_slot_combo'),
    sa.CheckConstraint("status IN ('pending', 'priced', 'accepted', 'rejected')", name='ck_custom_requests_status'),
    sa.ForeignKeyConstraint(['base_tier_id'], ['meal_tiers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_plan_requests_customer_id'), 'custom_plan_requests', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_menu_master_id'), table_name='menu_master')
    op.drop_index(op.f('ix_menu_master_menu_name'), table_name='menu_master')
    op.drop_table('menu_master')
    op.drop_table('weekly_menus')
    op.alter_column('credits', 'plan_end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('credits', 'is_manual',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('meal_tiers', 'slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('meal_tiers', 'diet_support',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True,
               existing_server_default=sa.text("'both'::character varying"))
    op.alter_column('meal_tiers', 'price_per_meal',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
    op.alter_column('meal_tiers', 'diet_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('meal_tiers', 'weekly_delivery_charge',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True,
               existing_server_default=sa.text('10.00'))
    op.alter_column('meal_tiers', 'monthly_delivery_charge',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('plan_templates', 'diet_type',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'both'::text"))
    op.alter_column('plan_templates', 'duration',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('plan_templates', 'slot_combo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_subscriptions_razorpay_order_id'), 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_razorpay_order_id'), 'subscriptions', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_razorpay_payment_id'), 'subscriptions', ['razorpay_payment_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'plan_templates', ['menu_id'], ['id'])
    op.alter_column('tier_pricing', 'diet_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('tier_pricing', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('users', 'reset_otp_expiry')
    op.alter_column('weekly_menu_images', 'diet_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('weekly_menu_images', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_menu_images', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('weekly_menu_images', 'diet_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.add_column('users', sa.Column('reset_otp_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('tier_pricing', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tier_pricing', 'diet_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_razorpay_payment_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_razorpay_order_id'), table_name='subscriptions')
    op.create_unique_constraint(op.f('uq_subscriptions_razorpay_order_id'), 'subscriptions', ['razorpay_order_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('plan_templates', 'slot_combo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('plan_templates', 'duration',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('plan_templates', 'diet_type',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'both'::text"))
    op.alter_column('meal_tiers', 'monthly_delivery_charge',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('meal_tiers', 'weekly_delivery_charge',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False,
               existing_server_default=sa.text('10.00'))
    op.alter_column('meal_tiers', 'diet_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('meal_tiers', 'price_per_meal',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    op.alter_column('meal_tiers', 'diet_support',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'both'::character varying"))
    op.alter_column('meal_tiers', 'slug',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('credits', 'is_manual',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('credits', 'plan_end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_table('weekly_menus',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('menu_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['meal_tiers.id'], name=op.f('weekly_menus_tier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('weekly_menus_pkey'))
    )
    op.create_table('menu_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('menu_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weekly_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthly_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weekly_delivery_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthly_delivery_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('menu_image', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('menu_master_pkey'))
    )
    op.create_index(op.f('ix_menu_master_menu_name'), 'menu_master', ['menu_name'], unique=False)
    op.create_index(op.f('ix_menu_master_id'), 'menu_master', ['id'], unique=False)
    op.drop_index(op.f('ix_custom_plan_requests_customer_id'), table_name='custom_plan_requests')
    op.drop_table('custom_plan_requests')
    # ### end Alembic commands ###
